### ISSUE TITLE
Ajuda.

### ISSUE THREAD

**Issue by Navelogic** [kadukitesesi/validacao-e-cadastro#1]
Opa, queria aprender sobre isso também. Pode me mandar um material (Youtube, artigo)

**Comment by kadukitesesi** [comment]
Boa tarde, é um assunto bem extenso e estou tentando ficar por dentro ainda, tentei achar conteúdos no youtube de brasileiros, mas achei meio corrido e muitas vezes desatualizado.

A documentação é ótima pra isso e bem completa e tem diversos guias que ainda estou explorando : https://spring.io/guides/gs/securing-web

Outra fonte é o baeldung, como se fosse o w3schools do spring e java: https://www.baeldung.com/security-spring

**Comment by Navelogic** [comment]
Ok, muito obrigado! Peguei um curso da Alura para estudar melhor sobre também!
